#!/bin/bash
. /usr/local/bin/set-env.bash

wait_on_thing () {
  local -r pid="${1}"
  local -r delay='0.75'
  local spinstr='\|/-'
  local temp
  what_to_wait_for=$1
  while true; do
    sudo grep -i "done" $what_to_wait_for  &> /dev/null
    if [[ "$?" -ne 0 ]]; then
      temp="${spinstr#?}"
      printf " [%c]  " "${spinstr}"
      spinstr=${temp}${spinstr%"${temp}"}
      sleep "${delay}"
      printf "\b\b\b\b\b\b"
    else
      break
    fi
  done
  printf "    \b\b\b\b"
  echo ""
}

show_progress()
{
  sleep 1
  echo -n 'Wait on Launch'
  wait_on_thing /tmp/launch.sh
  echo ' Launched'
  echo 'Install Gatsby'
  npm i -g gatsby-cli
  echo 'Gatsby has been installed'
  echo '<-- Press the continue button to proceed to the next step.'
}

show_progress
